export const DISPLAY_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
export const SUCCESS_ALERT = "SUCCESS_ALERT";
export const LOGIN_RED_ALERT = "LOGIN_RED_ALERT";
export const REGISTER_RED_ALERT = "REGISTER_RED_ALERT";
export const LOGIN_GREEN_ALERT = "LOGIN_GREEN_ALERT";
export const REGISTER_GREEN_ALERT = "REGISTER_GREEN_ALERT";
